apiVersion: tenantoperator.stakater.com/v1beta1
kind: Tenant
metadata:
  name: gabbar
spec:
  quota: nordmart-large
  owners:
    users:
      - rasheed@stakater.com
      - tehreem.nisa@stakater.com
      - bilal.bokharee@stakater.com
      - hanzala@stakater.com
      - shahid@stakater.com
      - asfa@stakater.com
      - mustafa@stakater.com
      - osama@stakater.com
      - julian.rubino@stakater.com
    groups:
      - azure-gabbar-owner
  editors:
    groups:
      - azure-gabbar-editor
  viewers:
    groups:
      - azure-gabbar-viewer
  argocd:
    sourceRepos:
      - 'https://github.com/stakater/nordmart-infra-gitops-config'
      - 'https://github.com/stakater/nordmart-apps-gitops-config'
      - 'https://nexus-helm-stakater-nexus.apps.devtest.vxdqgl7u.kubeapp.cloud/repository/helm-charts/'
  templateInstances:
  - spec:
      template: tenant-vault-access
      sync: true
  namespaces:
  - build
  - preview
  - dev
  - stage
  - prod
