apiVersion: tenantoperator.stakater.com/v1beta1
kind: Tenant
metadata:
  name: signport
spec:
  quota: nordmart-medium
  owners:
    users:
      - bilal.bokharee@stakater.com
      - hanzala@stakater.com
      - Magnus.Suther@knowit.se
      - tehreem.nisa@stakater.com
      - faizan@stakater.com
      - rasheed@stakater.com
  argocd:
    sourceRepos:
      - 'https://stakater.github.io/stakater-charts'
      - 'https://github.com/stakater/nordmart-infra-gitops-config'
      - 'https://github.com/stakater/nordmart-apps-gitops-config'
      - 'https://nexus-helm-stakater-nexus.apps.devtest.vxdqgl7u.kubeapp.cloud/repository/helm-charts/'
      - 'https://github.com/stakater/signport'
  namespaces:
  - dev
